SRC += msawatzky75.c

LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes
RGBLIGHT_ENABLE = no
TAP_DANCE_ENABLE = yes

AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
CONSOLE_ENABLE = no
SLEEP_LED_ENABLE = no
